export const reviewInfo = {
  '現代文': { size: 3 },
  '古文': { size:3 },
  '漢文': { size: 3 },
  '数学': { size: 3 },
  'Reading': { size: 3 },
  'Listening&Speaking': { size: 3 },
  'Writing': { size: 3 },
  '物理': { size: 3 },
  '化学': { size: 3 },
  '生物': { size: 3 },
  '日本史': { size: 3 },
  '世界史': { size: 3 },
  '地理': { size: 3 },
}